### ISSUE TITLE
HWK 1 Ex 3 submission

### ISSUE THREAD

**Issue by ChelseyGreen** [UWMadison-computingtools/coursedata#1]
Hi Professor @cecileane ,

I've committed my changes for hwk 1 exercise 3. I pushed it to git during class but forgot to open an issue ticket. I need to followup with you regarding removing some of the miscellaneous files from git that you mentioned. I will try to get a hold of you outside of class time or after class on Thursday.

Chelsey

**Comment by cecileane** [comment]
I am available most of tomorrow after 12 if you still need help removing these misc files. I'll be in Birge (341)
